---
title: "Client Report - Can You Predict That?"
subtitle: "Course DS 250"
author: "[Ryan Matthews]"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd 
import numpy as np
from lets_plot import *

# add the additional libraries you need to import for ML here

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here

# import your data here using pandas and the URL


url = https://raw.githubusercontent.com/byuidatascience/data4dwellings/master/data-raw/dwellings_ml/dwellings_ml.csv



from sklearn.tree import DecisionTreeClassifier


classifier_DT = DecisionTreeClassifier(max_depth=11)


classifier_DT.fit(X_train, y_train)


y_pred = classifier_DT.predict(X_test)


```

## Elevator pitch
_A SHORT (2-3 SENTENCES) PARAGRAPH THAT `DESCRIBES KEY INSIGHTS` TAKEN FROM METRICS IN THE PROJECT RESULTS THINK TOP OR MOST IMPORTANT RESULTS._ (Note: this is not a summary of the project, but a summary of the results.)

We received all of this data from you, what we have concluded from your data is that the most important part of it is that most houses on this list were born after 1980 not before and that most houses are two stories or more. In the analysis, we will show you how we ordered the data.

## QUESTION|TASK 1

__Create 2-3 charts that evaluate potential relationships between the home variables and `before1980`.__ Explain what you learn from the charts that could help a machine learning algorithm. 

_type your results and analysis here_

```{python}
# Include and execute your code here

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the CSV from the GitHub URL
url = "https://raw.githubusercontent.com/byuidatascience/data4dwellings/master/data-raw/dwellings_ml/dwellings_ml.csv"
df = pd.read_csv(url)

# Filter for houses built before 1980
df_pre1980 = df[df['yrbuilt'] < 1980]

# Set plot style
sns.set(style="whitegrid")

# 1. Histogram of year built (before 1980)
plt.figure(figsize=(10, 5))
sns.histplot(df_pre1980['yrbuilt'], bins=30, kde=True, color='skyblue')
plt.title('Distribution of Year Built (Before 1980)')
plt.xlabel('Year Built')
plt.ylabel('Number of Houses')
plt.show()

# 2. Scatter plot: basement square footage vs. finished basement
plt.figure(figsize=(10, 5))
sns.scatterplot(data=df_pre1980, x='bsmtsf', y='finbsmnt', hue='quality')
plt.title('Basement SF vs Finished Basement (Before 1980)')
plt.xlabel('Basement Square Footage')
plt.ylabel('Finished Basement (1 = Yes, 0 = No)')
plt.legend(title='Quality Score', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# 3. Boxplot: Quality by decade
df_pre1980['decade'] = (df_pre1980['yrbuilt'] // 10) * 10
plt.figure(figsize=(10, 5))
sns.boxplot(data=df_pre1980, x='decade', y='quality')
plt.title('Quality Scores by Decade (Before 1980)')
plt.xlabel('Decade Built')
plt.ylabel('Quality Score')
plt.show()










      


```


## QUESTION|TASK 2

__Build a classification model labeling houses as being built “before 1980” or “during or after 1980”.__ Your goal is to reach or exceed 90% accuracy. Explain your final model choice (algorithm, tuning parameters, etc) and describe what other models you tried.  

_type your results and analysis here_

```{python}
# Include and execute your code here


```


## QUESTION|TASK 3

__Justify your classification model by discussing the most important features selected by your model.__ This discussion should include a feature importance chart and a description of the features. 

_type your results and analysis here_

```{python}
# Include and execute your code here

```


## QUESTION|TASK 4

__Describe the quality of your classification model using 2-3 different evaluation metrics.__ You also need to explain how to interpret each of the evaluation metrics you use.  

_type your results and analysis here_

```{python}
# Include and execute your code here

```

---

## STRETCH QUESTION|TASK 1

__Repeat the classification model using 3 different algorithms.__ Display their Feature Importance, and Decision Matrix. Explian the differences between the models and which one you would recommend to the Client.   

_type your results and analysis here_

```{python}
# Include and execute your code here


```


## STRETCH QUESTION|TASK 2

__Join the `dwellings_neighborhoods_ml.csv` data to the `dwelling_ml.csv` on the `parcel` column to create a new dataset. Duplicate the code for the stretch question above and update it to use this data.__ Explain the differences and if this changes the model you recomend to the Client.   

_type your results and analysis here_

```{python}
# Include and execute your code here


```


## STRETCH QUESTION|TASK 3

__Can you build a model that predicts the year a house was built?__ Explain the model and the evaluation metrics you would use to determine if the model is good.  

_type your results and analysis here_

```{python}
# Include and execute your code here


```

---
