---
title: "Client Report - What's in a Name?"
subtitle: "Course DS 250"
author: "[Ryan Matthews]"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


## Project Notes

__For Project 1 the answer to each question should include a chart **and** a written response. The years labels on your charts should not include a comma. At least **two** of your charts must include reference marks.__  

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here


## QUESTION|TASK 1

__How does your name at your birth year compare to its use historically?__

_Ryan = Ryan was first used during medevil times when it first came to prominence as the name of Kings during the time period. It started being used by the Kings in the country of Ireland._


# Include and execute your code here
/Users/ryanmatthews/Desktop/Screen Shot 2025-05-10 at 10.41.20 PM.png
```


## QUESTION|TASK 2

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__


_If I talked to someone on the phone named Brittany, I would guess that she would be 24 years old. I would not guess anything older than that._

```{python}
# Include and execute your code here
Brittany=If I talked to someone on the phone named Brittany, I would guess that she would be 24 years old. I would not guess anything older than that.

```


## QUESTION|TASK 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names in a single chart. What trends do you notice?__

__


```{python}
# Include and execute your code here

```



## QUESTION|TASK 4

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__  

_type your results and analysis here_

```{python}
# Include and execute your code here


```

---

## STRETCH QUESTION|TASK 1

__Reproduce the chart Elliot using the data from the `names_year.csv` file.__ 

_type your results and analysis here_

```{python}
# Include and execute your code here


```


---
